SET search_path TO fairvalue, public;

INSERT INTO valuation_parameter_set (
    security_id,
    sector_template,
    parameter_type,
    parameter_key,
    parameter_value,
    effective_from,
    effective_to,
    source_note,
    created_at
)
VALUES
    (NULL, 'us_tech_compounder', 'wacc', 'base', '{"value":0.09}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'wacc', 'floor', '{"value":0.08}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'wacc', 'ceiling', '{"value":0.12}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'terminal_growth', 'base', '{"value":0.03}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'terminal_growth', 'floor', '{"value":0.025}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'terminal_growth', 'ceiling', '{"value":0.035}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'dcf', 'forecast_years', '{"value":5}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'dcf', 'initial_growth_cap', '{"value":0.22}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'dcf', 'growth_floor', '{"value":0.04}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'dcf', 'target_fcf_margin', '{"value":0.30}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_tech_compounder', 'relative', 'target_ev_ebitda', '{"value":24.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_tech_compounder', 'relative', 'target_pe', '{"value":30.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_general_quality', 'wacc', 'base', '{"value":0.095}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'wacc', 'floor', '{"value":0.085}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'wacc', 'ceiling', '{"value":0.125}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'terminal_growth', 'base', '{"value":0.025}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'terminal_growth', 'floor', '{"value":0.02}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'terminal_growth', 'ceiling', '{"value":0.03}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'dcf', 'forecast_years', '{"value":5}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'dcf', 'initial_growth_cap', '{"value":0.14}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'dcf', 'growth_floor', '{"value":0.03}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'dcf', 'target_fcf_margin', '{"value":0.22}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_general_quality', 'relative', 'target_ev_ebitda', '{"value":16.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_general_quality', 'relative', 'target_pe', '{"value":20.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_cyclical', 'wacc', 'base', '{"value":0.10}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'wacc', 'floor', '{"value":0.09}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'wacc', 'ceiling', '{"value":0.13}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'terminal_growth', 'base', '{"value":0.02}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'terminal_growth', 'floor', '{"value":0.015}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'terminal_growth', 'ceiling', '{"value":0.025}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'dcf', 'forecast_years', '{"value":5}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'dcf', 'initial_growth_cap', '{"value":0.10}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'dcf', 'growth_floor', '{"value":0.01}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'dcf', 'target_fcf_margin', '{"value":0.14}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_cyclical', 'relative', 'target_ev_ebitda', '{"value":12.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_cyclical', 'relative', 'target_pe', '{"value":15.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'wacc', 'base', '{"value":0.11}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'wacc', 'floor', '{"value":0.10}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'wacc', 'ceiling', '{"value":0.14}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'terminal_growth', 'base', '{"value":0.03}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'terminal_growth', 'floor', '{"value":0.02}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'terminal_growth', 'ceiling', '{"value":0.035}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'dcf', 'forecast_years', '{"value":6}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'dcf', 'initial_growth_cap', '{"value":0.30}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'dcf', 'growth_floor', '{"value":0.05}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'dcf', 'target_fcf_margin', '{"value":0.24}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD DCF model.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'relative', 'target_ev_ebitda', '{"value":26.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_hypergrowth_saas', 'relative', 'target_pe', '{"value":36.0}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD relative valuation.', NOW()),
    (NULL, 'us_tech_compounder', 'reverse_dcf', 'implied_growth_floor', '{"value":-0.05}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD reverse DCF.', NOW()),
    (NULL, 'us_tech_compounder', 'reverse_dcf', 'implied_growth_ceiling', '{"value":0.35}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD reverse DCF.', NOW()),
    (NULL, 'us_general_quality', 'reverse_dcf', 'implied_growth_floor', '{"value":-0.03}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD reverse DCF.', NOW()),
    (NULL, 'us_general_quality', 'reverse_dcf', 'implied_growth_ceiling', '{"value":0.25}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD reverse DCF.', NOW()),
    (NULL, 'us_cyclical', 'reverse_dcf', 'implied_growth_floor', '{"value":-0.08}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD reverse DCF.', NOW()),
    (NULL, 'us_cyclical', 'reverse_dcf', 'implied_growth_ceiling', '{"value":0.20}'::jsonb, CURRENT_DATE, NULL, 'Seeded template default for PRD reverse DCF.', NOW())
;
